### ISSUE TITLE
Fails to install with TypeError: 'Logger' object is not callable

### ISSUE THREAD

**Issue by jneo8** [canonical/charm-local-users#5]
Traceback (most recent call last):
  File "./src/charm.py", line 181, in <module>
    main(CharmLocalUsersCharm)
  File "/var/lib/juju/agents/unit-local-users-4/charm/venv/ops/main.py", line 426, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-local-users-4/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-local-users-4/charm/venv/ops/framework.py", line 276, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-local-users-4/charm/venv/ops/framework.py", line 736, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-local-users-4/charm/venv/ops/framework.py", line 783, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 88, in on_config_changed
    add_group(group)
  File "/var/lib/juju/agents/unit-local-users-4/charm/src/lib/local_users.py", line 252, in add_group
    log('creating group {0}'.format(group_name))
TypeError: 'Logger' object is not callable

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2022-04-01T08:01:25Z
 * owner: [dparv](https://launchpad.net/~dparv)
 * assignee: [dparv](https://launchpad.net/~dparv)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1967475)

**Comment by jneo8** [comment]
(by [dparv](https://launchpad.net/~dparv))
Fix released in channel edge revision 10
